version: "3"
services:
    db:
        image: postgres:latest
        container_name: postgres_typeorm_container
        restart: always
        ports:
            - "5431:5432"
        environment:
            POSTGRES_PASSWORD: "password"
        volumes:
            - ./data:/var/lib/postgresql/data